name: Release
# only trigger on tags, ‘verify‘ has already been triggered by push to PR
on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - name: Ensure tag is pushed to main branch
      run: |
        echo "ref: $GITHUB_REF"
        echo "base ref: ${{ github.ref }}"
        echo "sha: ${{ github.sha }}"

        branch=$(git branch -r --contains $GITHUB_SHA | grep origin/main || true)
        if [ -z "$branch" ]; then
          echo "❌ Tag is not pointing to main branch. Skipping."
          exit 1
        fi

    - uses: actions/checkout@v4

    - name: Parse version info from tag
      run: |
        # GITHUB_REF is like refs/tags/v2.3.5, so strip the first 11 chars
        VERSION=${GITHUB_REF:11}
        MAJOR=$(echo "$VERSION" | cut -d . -f 1)
        MINOR=$(echo "$VERSION" | cut -d . -f 2)
        PATCH=$(echo "$VERSION" | cut -d . -f 3)
        echo "version=$VERSION" >> $GITHUB_ENV
        echo "version_major=$MAJOR" >> $GITHUB_ENV
        echo "version_minor=$MINOR" >> $GITHUB_ENV
        echo "version_patch=$PATCH" >> $GITHUB_ENV

    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GH_TOKEN }}
        
    - run: |
        IMG="ghcr.io/${{github.repository}}"
        IMG=${IMG@L} # lower case the image
        docker build \
        --tag $IMG:${{ env.version }} \
        --tag $IMG:${{ env.version_major }}.${{ env.version_minor }}.latest \
        --tag $IMG:${{ env.version_major }}.latest \
        --tag $IMG:latest \
        .
        docker push --all-tags $IMG